#!/usr/bin/env python

#################################################
#     Siesta Tool Box - Suite                   #
# Developed by Dr. Carlos M. O. Bastos          #
#      bastoscmo.github.io                      #
#################################################

try:
    from importlib.metadata import version as _pkg_version
    VERSION = _pkg_version("stb_suite")
except Exception:
    VERSION = "1.9.5" 
from stb.cli import COLORS, color_text, show_intro

import os
import sys
import argparse
import numpy as np
import time

# Try to import sisl
try:
    import sisl
except ImportError:
    print("\n" + color_text("[CRITICAL ERROR] sisl library not found.", 'red'))
    print("Please install it using: pip install sisl")
    sys.exit(1)

def write_gnuplot_script(data_filename, output_filename, mode, axis_idx=2, pos_val=0.0):
    """
    Generates a .gplot script using the specific templates provided.
    - 3D: Based on '3dplot.gplot'
    - Slice: Based on 'plot.gplot'
    """
    gplot_name = output_filename.rsplit('.', 1)[0] + ".gplot"
    pdf_name = output_filename.rsplit('.', 1)[0] + ".pdf"
    
    axis_labels = ['X', 'Y', 'Z']
    fixed_axis = axis_labels[axis_idx]

    fileout = []
    fileout.append('# --- STB Plot Configuration ---\n')
    fileout.append('# Generated by plotdensity.py\n')
    
    # --- TEMPLATE: SLICE (Based on plot.gplot) ---
    if mode == 'slice':
        # Output setup
        fileout.append(f'set terminal pdfcairo enhanced color font "Arial,14" size 6,5\n')
        fileout.append(f'set output "{pdf_name}"\n')
        fileout.append('\n')

        # Logic to choose columns for 2D Map (X vs Y, X vs Z, Y vs Z)
        if axis_idx == 2:   # Fixed Z -> Plot X(1) vs Y(2)
            cols = "1:2:4"
            xl, yl = "X (Angstrom)", "Y (Angstrom)"
        elif axis_idx == 1: # Fixed Y -> Plot X(1) vs Z(3)
            cols = "1:3:4"
            xl, yl = "X (Angstrom)", "Z (Angstrom)"
        elif axis_idx == 0: # Fixed X -> Plot Y(2) vs Z(3)
            cols = "2:3:4"
            xl, yl = "Y (Angstrom)", "Z (Angstrom)"

        fileout.append(f'set title "Charge Density Slice ({fixed_axis}={pos_val:.2f} A)"\n')
        fileout.append(f'set xlabel "{xl}"\n')
        fileout.append(f'set ylabel "{yl}"\n')
        fileout.append('set cblabel "Rho (e/Ang^3)"\n')
        
        # Style from plot.gplot
        fileout.append('set size ratio -1\n')
        fileout.append('set tics out nomirror\n')
        fileout.append('set pm3d map\n')
        fileout.append('set pm3d interpolate 10,10  # Smoothing\n')
        
        # Palette: Blue -> White -> Red
        fileout.append('set palette defined (0 "#000099", 1 "#2255cc", 2 "#ffffff", 3 "#cc5522", 4 "#990000")\n')
        
        fileout.append(f'splot "{data_filename}" using {cols} with pm3d\n')

    # --- TEMPLATE: 3D (Based on 3dplot.gplot) ---
    else:
        # Output setup (PDF as requested)
        fileout.append(f'set terminal pdfcairo enhanced color font "Arial,12" size 8,6\n')
        fileout.append(f'set output "{pdf_name}"\n')
        fileout.append('\n')

        fileout.append('set title "3D Charge Density (Point Cloud)"\n')
        fileout.append('set xlabel "X (Angstrom)"\n')
        fileout.append('set ylabel "Y (Angstrom)"\n')
        fileout.append('set zlabel "Z (Angstrom)"\n')
        
        # Styles from 3dplot.gplot
        fileout.append('set view 60, 120, 1, 1\n')
        fileout.append('set size ratio -1\n')
        fileout.append('set ticslevel 0\n')
        
        # Depthorder and Fill
        fileout.append('set pm3d depthorder\n')
        fileout.append('set style fill solid 1.0 noborder\n')
        
        # Palette: Vibrant Spectrum
        fileout.append('set palette defined (0 "#2c7bb6", 1 "#00a6ca", 2 "#00ccbc", 3 "#90eb9d", 4 "#ffff8c", 5 "#f9d057", 6 "#f29e2e", 7 "#e76818", 8 "#d7191c")\n')
        
        # Note: 'pm3d' requires grid structure. 'points' works for volume clouds.
        # We use 'points' here to visualize the density cloud.
        fileout.append(f'splot "{data_filename}" using 1:2:3:4 with points palette pt 7 ps 0.4 title "Density"\n')

    with open(gplot_name, 'w') as f:
        f.writelines(fileout)
    
    print(f"[INFO] Gnuplot script saved to '{color_text(gplot_name, 'green')}'")
    print(f"[INFO] To plot: {color_text(f'gnuplot {gplot_name}', 'cyan')}")

def write_data_file(grid_data, lattice, origin, output_file, mode='3d', slice_idx=0, axis=2):
    """
    Writes grid data. For 'slice' mode, ensures block format for PM3D.
    """
    nx, ny, nz = grid_data.shape
    start_time = time.time()
    
    # --- 3D MODE ---
    if mode == '3d':
        print(f"[INFO] Mode: Full 3D Volume Export")
        print(f"[INFO] Processing {nx*ny*nz} grid points...")
        
        # Use vectorized operations for speed
        ix, iy, iz = np.meshgrid(range(nx), range(ny), range(nz), indexing='ij')
        
        # Coordinates
        frac_coords = np.vstack([ix.flatten()/nx, iy.flatten()/ny, iz.flatten()/nz]).T
        real_coords = origin + np.dot(frac_coords, lattice)
        values_flat = grid_data.flatten()
        
        # Combine
        data_to_save = np.column_stack([real_coords, values_flat])
        
        # Simple export for point cloud
        header_txt = "X Y Z Charge_Density"
        np.savetxt(output_file, data_to_save, fmt='%.6f %.6f %.6f %.6e', header=header_txt)

    # --- 2D MAP MODE (Slice) ---
    elif mode == 'slice':
        axis_names = ['X', 'Y', 'Z']
        print(f"[INFO] Mode: 2D Map (Slice)")
        print(f"[INFO] Mapping plane perpendicular to {axis_names[axis]} axis at Index {slice_idx}")
        
        with open(output_file, 'w') as f:
            f.write(f"# Generated by STB. Format: X Y Z Charge_Density\n")
            
            # Select iteration ranges based on which axis is fixed
            if axis == 2:   # Cut along Z (XY Plane)
                u_range, v_range = range(nx), range(ny)
                i_fixed = slice_idx
            elif axis == 1: # Cut along Y (XZ Plane)
                u_range, v_range = range(nx), range(nz)
                i_fixed = slice_idx
            elif axis == 0: # Cut along X (YZ Plane)
                u_range, v_range = range(ny), range(nz)
                i_fixed = slice_idx
            
            # Nested loop to create PM3D blocks (Blank line separation)
            for i in u_range:
                for j in v_range:
                    if axis == 2: ix, iy, iz = i, j, i_fixed
                    elif axis == 1: ix, iy, iz = i, i_fixed, j
                    elif axis == 0: ix, iy, iz = i_fixed, i, j
                    
                    frac_coords = np.array([ix/nx, iy/ny, iz/nz])
                    real_pos = origin + np.dot(frac_coords, lattice)
                    val = grid_data[ix, iy, iz]
                    
                    f.write(f"{real_pos[0]:.6f} {real_pos[1]:.6f} {real_pos[2]:.6f} {val:.6e}\n")
                
                f.write("\n") # Blank line for PM3D structure

    elapsed = time.time() - start_time
    print(f"[INFO] Write completed in {elapsed:.2f} seconds.")

def main():
    parser = argparse.ArgumentParser(
        description="Convert SIESTA RHO density to Gnuplot 2D Maps/3D Clouds.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    
    parser.add_argument("-l", "--label", required=True, help="System Label (looks for .RHO file)")
    parser.add_argument("-o", "--output", default="density_plot.dat", help="Output data filename")
    parser.add_argument("--3d", action="store_true", dest="full_3d", help="Export full 3D volume")
    parser.add_argument("-a", "--axis", type=int, default=2, choices=[0,1,2], help="Axis normal to the map (0=X, 1=Y, 2=Z)")
    parser.add_argument("-p", "--pos", type=float, help="Position (Angstrom) of the 2D cut")
    
    parser.add_argument("--no-intro", dest="intro", action="store_false", help="Skip intro")
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")

    args = parser.parse_args()
    filename = f"{args.label}.RHO"
    
    if args.intro:
        show_intro()

    print("\n" + color_text("DENSITY PLOTTER:", 'bold'))
    print("-" * 60)
    
    if not os.path.exists(filename):
        print(f"{COLORS['red']}[ERROR] File '{filename}' not found.{COLORS['reset']}")
        sys.exit(1)

    print(f"[INFO] Reading: {color_text(filename, 'cyan')}")
    try:
        try:
            sile = sisl.get_sile(filename)
        except AttributeError:
            sile = sisl.get_io(filename)
        grid_obj = sile.read_grid()
    except Exception as e:
        print(f"{COLORS['red']}[FATAL] {e}{COLORS['reset']}")
        sys.exit(1)

    grid_data = grid_obj.grid
    try:
        lattice = grid_obj.geometry.lattice.cell 
    except AttributeError:
        lattice = grid_obj.lattice.cell
    origin = grid_obj.origin
    nx, ny, nz = grid_data.shape

    print(f"[INFO] Grid: {nx}x{ny}x{nz}")

    mode = '3d' if args.full_3d else 'slice'
    slice_idx = 0
    pos_val = 0.0

    if mode == 'slice':
        dim_size = [nx, ny, nz][args.axis]
        if args.pos is not None:
            axis_vec = lattice[args.axis]
            axis_len = np.linalg.norm(axis_vec)
            slice_idx = int(round((args.pos / axis_len) * dim_size))
            pos_val = args.pos
        else:
            slice_idx = dim_size // 2
            pos_val = (slice_idx / dim_size) * np.linalg.norm(lattice[args.axis])
            print(f"{COLORS['yellow']}[NOTICE] Using center of axis {args.axis}: {pos_val:.2f} A{COLORS['reset']}")

        if slice_idx < 0 or slice_idx >= dim_size:
            print(f"{COLORS['red']}[ERROR] Position out of bounds.{COLORS['reset']}")
            sys.exit(1)

    write_data_file(grid_data, lattice, origin, args.output, mode, slice_idx, args.axis)
    write_gnuplot_script(args.output, args.output, mode, args.axis, pos_val)

    print("\n[INFO] Complete job!") 
    print("\n"+"-"*60)
    print(color_text("Density mapped. I am your density (destiny).\n\n", 'bold'))

if __name__ == "__main__":
    main()
